version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /var/app/node_modules
      - .:/var/app
      # - type: bind
      #   source: ./
      #   target: /var/app
    environment:
      - WATCHPACK_POLLING=true
  
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /var/app/node_modules
      - .:/var/app
    environment:
      - WATCHPACK_POLLING=true
    command: ["npm","run","test"] 